### ISSUE TITLE
ImportError: No module named Quartz - Mac OSX

### ISSUE THREAD

**Issue by Joebob12** [SavinaRoja/PyUserInput#13]
I must be a moron but by quartz does that mean 
http://xquartz.macosforge.org/landing/
Because I installed it and still end up with this error:
ImportError: No module named Quartz
There is no pip module named quartz, so if you guys could help me figure this out it would be much appreciated.

**Comment by shixudongleo** [comment]
pip install pyobjc-framework-Quartz

**Comment by shixudongleo** [comment]
pip install pyobjc-framework-Quartz

**Comment by chestervdb** [comment]
thanks @shixudongleo, it worked here

**Comment by jjconti** [comment]
the pip installation fails with this error:

building 'Foundation._Foundation' extension

clang -Wno-unused-result -Werror=declaration-after-statement -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/sqlite/include -Ibuild/temp.macosx-10.9-x86_64-3.4/pyobjc-include -I/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c Modules/_Foundation.m -o build/temp.macosx-10.9-x86_64-3.4/Modules/_Foundation.o -DPyObjC_BUILD_RELEASE=1010 -Wno-deprecated-declarations -isysroot /

In file included from Modules/_Foundation.m:15:

Modules/_Foundation_protocols.m:14:28: error: cannot find protocol declaration for 'NSProgressReporting'

    p = PyObjC_IdToPython(@protocol(NSProgressReporting)); Py_XDECREF(p);

                           ^

Modules/_Foundation_protocols.m:15:28: error: cannot find protocol declaration for 'NSURLSessionStreamDelegate'

    p = PyObjC_IdToPython(@protocol(NSURLSessionStreamDelegate)); Py_XDECREF(p);

                           ^

2 errors generated.

error: command 'clang' failed with exit status 1

**Comment by pepijndevos** [comment]
Seems to be a pyobjc error.‎ Can you try installing that separately?

**Comment by jjconti** [comment]
$ pip3 install pyobj
Downloading/unpacking pyobj
  Downloading pyobj-1.0.tar.gz
  Running setup.py (path:/private/var/folders/1k/c_s9bcbs30d570m419fwpx140000gn/T/pip_build_juanjo/pyobj/setup.py) egg_info for package pyobj
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/1k/c_s9bcbs30d570m419fwpx140000gn/T/pip_build_juanjo/pyobj/setup.py", line 4, in <module>
        from web import __version__
    ImportError: No module named 'web'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/1k/c_s9bcbs30d570m419fwpx140000gn/T/pip_build_juanjo/pyobj/setup.py", line 4, in <module>

    from web import __version__

ImportError: No module named 'web'

**Comment by faytom** [comment]
@shixudongleo +1
