### ISSUE TITLE
Is PyUserInput works on all fedora,RedHat related or debian related os

### ISSUE THREAD

**Issue by DhairyashilBhosale** [SavinaRoja/PyUserInput#51]
Hi I am new to python ,so can we use PyUserInput on fedora or redhat related os , I am using Debian 7 and PyuserInput is working fine . for installing PyuserInput I use 'pip install PyuserInput' but for fedora related os, is this command works fine ? means fedora and redhat use rpm and yum so , is that possible to use pip on fedora related os. and How can we install PyuserInput and python-xlib on fedora related os?
Regards,
Dhairyashil

**Comment by pepijndevos** [comment]
I believe so, yes.
