### ISSUE TITLE
Including PyUserInput in another project

### ISSUE THREAD

**Issue by TimSmith714** [SavinaRoja/PyUserInput#57]
Hi
Apologies for what is very much a beginners question. I was hoping to include PyUserInput in a project I'm working on https://github.com/TimSmith714/Remote-MC-Control It's a remote control solution for Minecraft inspired by wanting to help a disabled friend play Minecraft using her Eye Tracking software. I'm not sure how I'd go about arranging the PyUserInput files in the project folder to make sure that I leave all the proper licenses in the proper place. Should I create a PyUserInput folder to include the files as they are here?
Thanks
Tim

**Comment by pepijndevos** [comment]
Are you familiair with pip and virtualenv?

    virtualenv env
    env/bin/activate
    pip install pyuserinput

I would personally not worry to much about the licences.

**Comment by TimSmith714** [comment]
Hi, thanks for the response I'll give that a go
