### ISSUE TITLE
Execution with start() directly terminate

### ISSUE THREAD

**Issue by userems** [SavinaRoja/PyUserInput#70]
Hi,

following this issue https://github.com/SavinaRoja/PyUserInput/issues/41 I want to capture mouse movement and keyboard input.
As suggested I used start() instead of run() but directly after executing with 'python logger.py' the application terminates.
system: Ubuntu 15.04 64bit, python 2.7.9

My code
```
from pymouse import PyMouseEvent

class MouseOne(PyMouseEvent):
	def __init__(self):
	  PyMouseEvent.__init__(self)
	
	def click(self, x, y, button, press):
		print "click"

m = MouseOne()
m.start()
```

**Comment by pepijndevos** [comment]
Python shuts down after all non-daemon threads finish. So either you need to `m.daemon = False` or give the main thread som busywork, like `time.sleep`.

**Comment by userems** [comment]
Thank you,  ```m.daemon=False``` works perfectly fine.
