### ISSUE TITLE
How to simulate a space bar hit?

### ISSUE THREAD

**Issue by shushi2000** [SavinaRoja/PyUserInput#71]
This is a question I have rather than an actual issue.

I would like to do a sequence of keyboard input like:

press and hold 'Alt'
hit 'Space'
release 'Alt'
hit 'X'

But I am confused how to make the Space key work. Could you please show me how to do it?

**Comment by SavinaRoja** [comment]
Currently unable to test, but can correspond. Could you give the following approach a try?

    from pykeyboard import PyKeyboard

    mykeyboard = PyKeyboard()

    mykeyboard.press_key('Alt_L')
    mykeyboard.tap_key(' ')
    mykeyboard.release_key('Alt_L')
    mykeyboard.tap_key('X')

**Comment by pepijndevos** [comment]
Is this still an issue? Please reopen in that case.
