### ISSUE TITLE
Old version in pip

### ISSUE THREAD

**Issue by virajkanwade** [SavinaRoja/PyUserInput#72]
A fix in Oct 2014 is still missing in pip install.

**Comment by pepijndevos** [comment]
I don;t have access to PyPi for this project I think :/

**Comment by Duality4Y** [comment]
i always just do:
```
    pip install git+https://github.com/SavinaRoja/PyUserInput
```
to get the latest version

**Comment by pepijndevos** [comment]
I recently pushed a new version to PyPi, so I'm closing this.

**Comment by Duality4Y** [comment]
good point, but the same goes for that :)
