### ISSUE TITLE
PyMouse.drag error

### ISSUE THREAD

**Issue by MacHu-GWU** [SavinaRoja/PyUserInput#90]
https://github.com/SavinaRoja/PyUserInput/blob/master/pymouse/windows.py, line 72

```
    def drag(self, x, y):
        self.press(*m.position()) # this should be self.press(*self.position())
        #self.move(x, y)
        self.release(x, y)  
```

**Comment by pepijndevos** [comment]
This repo is out of date. Fixed upstream.

https://github.com/PyUserInput/PyUserInput/blob/master/pymouse/windows.py#L73

**Comment by MacHu-GWU** [comment]
But if I use ``pip install PyUserInput``, what I installed is the wrong one. You should update tihs fix to PyPI also
