### ISSUE TITLE
Arrow Keys, Esc and Num Pad Keys? (Linux)

### ISSUE THREAD

**Issue by deysumitkr** [SavinaRoja/PyUserInput#96]
How can we send **Arrow Keys** (Up, Down, Left, Right), **Esc** and **NumPad Keys**?
Is it possible to send CapsLock and NumLock keys as well?

[Platform: Ubuntu]

**Comment by pepijndevos** [comment]
You can send the key codas directly, but there is no easy mapping like there is for printable ascii.

**Comment by deysumitkr** [comment]
Okay Found it!
All special keys are mentioned in [pykeyboard/x11.py](https://github.com/SavinaRoja/PyUserInput/blob/master/pykeyboard/x11.py)
